### ISSUE TITLE
API Service

### ISSUE THREAD

**Issue by GianCastle** [Emplea-do/admin.emplea.do#16]
Write a service that...

### **CAN**

**GET**

#### A list
- Employers jobs
- Jobs filter by their status (_approved_ or _dismissed_)
- Jobs filter by the employer (❓)
- Jobs filter by date (❓)

**POST**
#### A new
- Job employer request
- Job employee proposal (❓)
- Sign up user
- Sign in session

#### A change (PUT, PATCH)
- Job employer request 

@amaurygomez  @claudiosanchez 
If anything's missing, please let me know.

**Cheers! 🥳**

**Comment by claudiosanchez** [comment]
I'd suggest adding something to the tittle so that it is apparent if it is "JS level service" or a "Backend/API".
