### ISSUE TITLE
Edit a Job Page

### ISSUE THREAD

**Issue by GianCastle** [Emplea-do/admin.emplea.do#26]

**Comment by mecm1993** [comment]
@GianCastle I would like to work on this.

**Comment by mecm1993** [comment]
For now, the **API** does not return a response after the _update_ is called. Below an example of the _update_ request,

```js
update: (resource, params) =>
    request(`${prepareUrl}/${resource}/${params.id}`, {
      method: 'PUT',
      body: JSON.stringify(params.data),
    }).then(({ json }) => ({ data: json })),
```
After the request, the framework expects a response (object which contains `id` & `data`) from the server.

**Comment by GianCastle** [comment]
LGTM! 🥳

But... 👀

We need to work some related tasks on the backend side so then we can ensure this MR gets passed. 

Right now, @amaurygomez is working on the API. The repository still private since we continuing addressings some issues (like documentation and some project scafolding details)


@amaurygomez As soon as you can, please provide us an status of the backend.
