### ISSUE TITLE
Delete a Job

### ISSUE THREAD

**Issue by GianCastle** [Emplea-do/admin.emplea.do#28]

**Comment by mecm1993** [comment]
@GianCastle I would like to work on this.

**Comment by mecm1993** [comment]
Currently, the API returns a **Bad Request** when delete is called. Below an example of the delete request,

```js
delete: (resource, params) =>
    request(`${prepareUrl}/${resource}/${params.id}`, {
      method: 'DELETE',
    }).then(({ json }) => ({ data: json })),
```

I am not sure if there is API documentation (Swagger or any other), so for future features the contributors know in advance about the API.
